# Site settings

locale                   : "en-US"
title                    : "Local Preservation School: Handbook"
email: info@baltimoreheritage.org
title_separator          : "-"
name                     : "Local Preservation School"
description              : "Tools, resources, and tutorials on saving historic places in your community."
url                      : "https://localpreservation.github.io" # the base hostname & protocol for your site
baseurl                  : "/handbook" # the subpath of your site
repository               : "localpreservation/handbook" # GitHub username/repo-name

# Collections
#collections:
#  books:
#    output: false

sass:
  style: compressed


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
  - _site
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
